language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  min_ngram: 1
  max_ngram: 2
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 5
- name: DIETClassifier
  epochs: 100  # Increased for better training
  constrain_similarities: true
  model_confidence: softmax
  hidden_layers_sizes:
    text: [512, 256]  # Increased layer size
    label: [256, 128]
  weight_sparsity: 0.3
  batch_strategy: balanced
  evaluate_on_number_of_examples: 0  # Disable test set evaluation during training
  evaluate_every_number_of_epochs: 5
  checkpoint_model: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100  # Increased for better training
  retrieval_intent: faq
  scale_loss: true
- name: FallbackClassifier
  threshold: 0.6  # Decreased to catch more uncertain predictions
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
  max_history: 5  # Increased memory
- name: TEDPolicy
  max_history: 5  # Increased history
  epochs: 100  # Increased for better training
  constrain_similarities: true
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100  # Increased for better training
  tolerance: 0.2  # Decreased tolerance for better discrimination

assistant_id: 20250327-133050-khaki-limit

training:
  batch_size: 64  # Increased for faster training
  validation_split: 0.2
  evaluation_interval: 5
  cache_featurizer: true
  random_seed: 42  # Add deterministic behavior